views/groups.py
from flask import Blueprint, render_template

from common.database import Database


groups_blueprint = Blueprint('groups', __name__)

@groups_blueprint.route('/', methods=['POST', 'GET'])
def index():
    # return users without words dictionary
    users = Database.all("users", {"words": 0})

    # 0 is for global, maybe in the future indv groups
    # sort users according to total points
    sorted_users = sorted(users, key=lambda d: d["groups"][0]["total_points"], reverse=True)


    return render_template('groups/main.html', users=sorted_users)

views/how_to_play.py
from flask import Blueprint, render_template


how_to_play_blueprint = Blueprint('how_to_play', __name__)


@how_to_play_blueprint.route('/how_to_play', methods=['POST', 'GET'])
def index():

    return render_template("howtoplay/how_to_play.html")

views/play.py
from datetime import timedelta, datetime, date


from flask import Blueprint, render_template, request, session, flash


from common.database import Database
from models.Check import Check
from models.user.decorators import requires_login

play_blueprint = Blueprint('play', __name__)


def letters_f(req, num):

    """"
        returns the input from the form if POST in a list
    """

    if req == "POST":
        letters = []
        for i in range(1, num + 1):
            temp = "letter" + str(i)
            let = request.form.get(temp)
            letters.append(let.upper())

        return True, letters
    return False, []


def check_f(letters, num):

    """"
        checks the input against the word of the day via the Check class
    """

    check = Check(letters)
    if check.allowed():
        state, points_add = check.correct_word()
        check.check()


        if state:
            now = datetime.now()
            today = now.date()
            today_s = today.strftime("%Y%m%d")
            data = Database.find_one("dicts", {"name": str(num)})
            list_dict = data["random"]
            today_word = list_dict[today_s]
            return True, today_word, points_add
        else:
            return False, '', 0
    else:
        flash('Please enter a valid word', 'danger')
        return False, '', 0


def page_vars(num):

    # get todays date string
    now = datetime.now()
    today = now.date()
    today_s = today.strftime("%Y%m%d")

    #load in users data excluding the words dict
    user_data = Database.find_one_return_one('users', {"email": session['email']}, {f"words.{today_s}": 1})
    alphabet = user_data["words"][today_s][num-3]["dict"]
    guesses = user_data["words"][today_s][num-3]["guesses"]
    state_bool = user_data["words"][today_s][num-3][str(num)]

    # calculate time till new word, maybe can do this in java ???
    today = datetime.combine(date.today(), datetime.min.time())
    tomorrow = today + timedelta(days=1)
    time = (tomorrow - datetime(1970, 1, 1)).total_seconds()

    return alphabet, guesses, state_bool, time


# can we make all these urls a single function?
@play_blueprint.route('/3letters', methods=['POST', 'GET'])
@requires_login
def letters_3():

    points = [30, 20, 15, 10, 5]
    num = 3
    req = request.method

    bool_post, letters = letters_f(req, num)

    if bool_post:
        bool_check, today_word, points_add = check_f(letters, num)

        if bool_check:
            return render_template("play/correct.html", word=today_word, points=points_add)

    alphabet, guesses, state_bool, time = page_vars(num)

    return render_template("play/main.html", alphabet=alphabet, length=num, guesses=guesses, points=points,
                           state_bool=state_bool, time=time)


@play_blueprint.route('/4letters', methods=['POST', 'GET'])
@requires_login
def letters_4():
    points = [30, 20, 15, 10, 5]
    num = 4
    req = request.method

    bool_post, letters = letters_f(req, num)

    if bool_post:
        bool_check, today_word, points_add = check_f(letters, num)

        if bool_check:
            return render_template("play/correct.html", word=today_word, points=points_add)

    alphabet, guesses, state_bool, time = page_vars(num)

    return render_template("play/main.html", alphabet=alphabet, length=num, guesses=guesses, points=points,
                           state_bool=state_bool, time=time)


@play_blueprint.route('/5letters', methods=['POST', 'GET'])
@requires_login
def letters_5():
    points = [30, 20, 15, 10, 5]
    num = 5
    req = request.method

    bool_post, letters = letters_f(req, num)

    if bool_post:
        bool_check, today_word, points_add = check_f(letters, num)

        if bool_check:
            return render_template("play/correct.html", word=today_word, points=points_add)

    alphabet, guesses, state_bool, time = page_vars(num)

    return render_template("play/main.html", alphabet=alphabet, length=num, guesses=guesses, points=points,
                           state_bool=state_bool, time=time)


@play_blueprint.route('/6letters', methods=['POST', 'GET'])
@requires_login
def letters_6():
    points = [40, 30, 20, 15, 10, 5]
    num = 6
    req = request.method

    bool_post, letters = letters_f(req, num)

    if bool_post:
        bool_check, today_word, points_add = check_f(letters, num)

        if bool_check:
            return render_template("play/correct.html", word=today_word, points=points_add)

    alphabet, guesses, state_bool, time = page_vars(num)

    return render_template("play/main.html", alphabet=alphabet, length=num, guesses=guesses, points=points,
                           state_bool=state_bool, time=time)


@play_blueprint.route('/7letters', methods=['POST', 'GET'])
@requires_login
def letters_7():
    points = [40, 30, 20, 15, 10, 5]
    num = 7
    req = request.method

    bool_post, letters = letters_f(req, num)

    if bool_post:
        bool_check, today_word, points_add = check_f(letters, num)

        if bool_check:
            return render_template("play/correct.html", word=today_word, points=points_add)

    alphabet, guesses, state_bool, time = page_vars(num)

    return render_template("play/main.html", alphabet=alphabet, length=num, guesses=guesses, points=points,
                           state_bool=state_bool, time=time)


@play_blueprint.route('/8letters', methods=['POST', 'GET'])
@requires_login
def letters_8():
    points = [40, 30, 20, 15, 10, 5]
    num = 8
    req = request.method

    bool_post, letters = letters_f(req, num)

    if bool_post:
        bool_check, today_word, points_add = check_f(letters, num)

        if bool_check:
            return render_template("play/correct.html", word=today_word, points=points_add)

    alphabet, guesses, state_bool, time = page_vars(num)

    return render_template("play/main.html", alphabet=alphabet, length=num, guesses=guesses, points=points,
                           state_bool=state_bool, time=time)


@play_blueprint.route('/9letters', methods=['POST', 'GET'])
@requires_login
def letters_9():
    points = [40, 30, 20, 15, 10, 5]
    num = 9
    req = request.method

    bool_post, letters = letters_f(req, num)

    if bool_post:
        bool_check, today_word, points_add = check_f(letters, num)

        if bool_check:
            return render_template("play/correct.html", word=today_word, points=points_add)

    alphabet, guesses, state_bool, time = page_vars(num)

    return render_template("play/main.html", alphabet=alphabet, length=num, guesses=guesses, points=points,
                           state_bool=state_bool, time=time)

views/users.py
from flask import Blueprint, render_template, request, url_for, redirect, session, flash

from common.database import Database
from common.utils import Utils
from models.user.user import User

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/signup', methods=['POST', 'GET'])
def register_user():

    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        name = request.form["name"]

        if email == "" or password == "" or name == "":
            flash("Please don't leave any fields blank.", "danger")
            return redirect(url_for('.register_user'))
        elif not Utils.email_is_valid(email):
            flash('The e-mail does not have the right format test@test.com')
        else:

            if User.is_email_used(email):
                User.register_user(email, password, name)
                session['email'] = email
                return redirect(url_for('.welcome'))
            else:
                flash('The e-mail you used to register already exists', 'danger')

    return render_template('users/signup.html')


@user_blueprint.route('/welcome', methods=['POST', 'GET'])
def welcome():

    user = Database.find_one("users", {"email": session['email']})

    return render_template('welcome.html', name=user["name"])


@user_blueprint.route('/login', methods=['POST', 'GET'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        if email == "" or password == "":
            flash("Please enter your email and password", "danger")
            return redirect(url_for('.login_user'))

        else:

            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for('.welcome'))
            else:
                flash("Your password was incorrect.", "danger")

    return render_template('users/login.html')

@user_blueprint.route('/logout')
def log_out():
    session['email'] = None
    return redirect(url_for('.login_user'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8" name="viewport" content="width=device-width">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>WordMaster</title>
    <link rel="stylesheet" href="../static/CSS/design2.css"/>

</head>

<body>

    <div class="navbar">
        <div class="container">

            <img class="logo-img"src="../static/images/logo.svg" alt="Logo">
            <img class="logo-img-mobile"src="../static/images/mobile/logo.svg" alt="Logo">
            <a class="logo-word" id="logo" href="{{ url_for('home') }}">WORD <span>MASTER</span></a>
            <img  class="mobile-menu" id="mobile-menu" src="../static/images/mobile/menu.svg" alt="Open Navigation">


            <nav >

                <img id="mobile-exit" class="mobile-menu-exit" src="../static/images/mobile/exit.svg" alt="Close mobile menu exit">

       <ul class="primary-nav">
                        <li>
                            <div class="dropdown">
                              <span class="drop-span">Play</span>
                                  <div class="dropdown-content">

                                      <a href="{{ url_for('play.letters_3') }}">3 letters</a>
                                      <a href="{{ url_for('play.letters_4') }}">4 letters</a>
                                      <a href="{{ url_for('play.letters_5') }}">5 letters</a>
                                      <a href="{{ url_for('play.letters_6') }}">6 letters</a>
                                      <a href="{{ url_for('play.letters_7') }}">7 letters</a>
                                      <a href="{{ url_for('play.letters_8') }}">8 letters</a>
                                      <a href="{{ url_for('play.letters_9') }}">9 letters</a>


                                  </div>
                            </div>
                        </li>
                    <li><a  href="{{ url_for('groups.index') }}">Groups</a></li>
                    <li><a  href="{{ url_for('how_to_play.index') }}">How to Play</a></li>
                </ul>

                <ul class="secondary-nav">
                    <li><a href="{{ url_for('users.login_user') }}">Log in</a></li>
                    <li><a href="{{ url_for('users.log_out') }}">Log out</a></li>
                    <li class="nav-sign-up"><a   href="{{ url_for('users.register_user') }}">Sign up</a></li>
                </ul>

            </nav>
        </div>
    </div>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}

                <div class="alerts" role="alert" align="center">
                    {{ message }}
                </div>

            {% endfor %}
        {% endif %}
    {% endwith %}




    <script>

        const mobileBtn = document.getElementById('mobile-menu')
        const nav = document.querySelector('nav');
        const mobileBtnExit = document.getElementById('mobile-exit');

        mobileBtn.addEventListener('click', () => {
            nav.classList.add('menu-active');
        })

        mobileBtnExit.addEventListener('click', () => {
            nav.classList.remove('menu-active');
        })

        $("#prospects_form").submit(function(e) {
            e.preventDefault(); // <==stop page refresh==>
        });

    </script>

 {% block content %}

{% endblock %}


</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block content %}

    <section class="main">
        <div class="container-main">
            <h1>Welcome to <br><span class="word">Word</span><span class="home-master">Master</span></h1>
            <h3>Are you <span class="home-smart">smart</span> enough? <br>Do you have what it takes?</h3>

            <div class="example">
                <img class= "example-img" src="../static/images/example.svg" alt="Example">
            </div>

           <div class="btn-get">
                <button class="btn-get-started"> <a href="{{ url_for('users.register_user') }}">Get Started</a></button>
           </div>
        </div>
    </section>

{% endblock %}

templates/welcome.html
{% extends "base.html" %}

{% block content %}

    <style>

        .correct {
            display: flex;
            text-align: center;
            margin: auto;
            width: 100%;
            margin-bottom: 12px;
        }



        .guess1 {
            display: flex;
            text-align: center;
            margin: auto;
        }

    </style>

    <h1>Welcome</h1>

    <div class="correct">

        <div class="guess1">

            {% for let in name %}

            <span class="letter-correct">{{ let }}</span>

            {% endfor %}

        </div>
    </div>

    <h2>to WordMaster.</h2>
    <h2>I hope you have fun </h2>
    <h2> and enjoy!!! </h2>

    <div class="btn-get">
        <button class="btn-play"><a   href="{{ url_for('play.letters_3') }}">Play Now</a></button>
    </div>



{% endblock %}